export const menus = [
  {
    id: '1',
    type: 0,
    sort: 1,
    visible: 1,
    name: 'System',
    path: '/system',
    component: 'Layout',
    meta: { title: '系统管理', icon: '' },
    children: [
      {
        id: '1-1',
        type: 1,
        sort: 1,
        visible: 1,
        name: 'User',
        path: '/user',
        component: 'System/UserManage/index',
        meta: { title: '用户管理', icon: '' },
      },
      {
        id: '1-2',
        type: 1,
        sort: 2,
        visible: 1,
        name: 'Role',
        path: '/role',
        component: 'System/RoleManage/index',
        meta: { title: '角色管理', icon: '' },
      },
    ],
  },
  {
    id: '2',
    type: 0,
    sort: 2,
    visible: 1,
    name: 'Example',
    path: '/example',
    component: 'Layout',
    meta: { title: '示例', icon: '' },
    children: [],
  },
  {
    id: '3',
    type: 0,
    sort: 3,
    visible: 0,
    name: 'Example2',
    path: '/example2',
    component: 'Layout',
    meta: { title: '示例2', icon: '' },
    children: [],
  },
]
